import {
  Activity,
  AlertCircle,
  BadgeDollarSign,
  BookCheck,
  BriefcaseBusiness,
  Building2,
  ClipboardCheck,
  FileSearch,
  FileWarning,
  FolderLock,
  Landmark,
  LayoutDashboard,
  Scale,
  ShieldAlert,
  Target,
  UserCog,
  Users,
  Wallet,
} from 'lucide-react';
import { getList, getRecord, postRecord } from '../lib/http';
import { schemaFromFields } from '../lib/forms';
import { permissions } from '../lib/permissions';
import type { ModuleDefinition } from '../lib/module-types';

export const moduleRegistry: ModuleDefinition[] = [
  {
    route: '/',
    title: 'Dashboard',
    description: 'Operational overview across the platform.',
    icon: LayoutDashboard,
  },
  {
    route: '/users',
    title: 'Users and roles',
    description: 'Identity provisioning, access change requests, password resets, and MFA administration.',
    icon: UserCog,
    navPermission: permissions.identityUsersRead,
    mutations: [
      {
        key: 'create-user',
        title: 'Create user',
        description: 'Provision a new internal user with a temporary password. Role grants still flow through maker-checker approval.',
        permission: permissions.identityUsersCreate,
        fields: [
          { name: 'email', label: 'Email', type: 'email', required: true },
          { name: 'displayName', label: 'Display name', type: 'text', required: true },
          { name: 'temporaryPassword', label: 'Temporary password', type: 'password', required: true },
        ],
        schema: schemaFromFields([
          { name: 'email', label: 'Email', type: 'email', required: true },
          { name: 'displayName', label: 'Display name', type: 'text', required: true },
          { name: 'temporaryPassword', label: 'Temporary password', type: 'password', required: true },
        ]),
        submit: (values) => postRecord('/api/users', values),
      },
      {
        key: 'request-access-change',
        title: 'Raise access change',
        description: 'Submit a role assignment or deactivation request into the maker-checker approval workflow.',
        permission: permissions.identityAccessChangeRequest,
        fields: [
          { name: 'targetUserId', label: 'Target user ID', type: 'text', required: true },
          {
            name: 'changeType',
            label: 'Change type',
            type: 'select',
            required: true,
            options: [
              { label: 'RoleAssignment', value: 'RoleAssignment' },
              { label: 'UserDeactivation', value: 'UserDeactivation' },
            ],
          },
          { name: 'roleNames', label: 'Role names', type: 'tags', placeholder: 'SystemAdmin,InternalAuditor' },
          { name: 'reason', label: 'Reason', type: 'textarea', required: true, rows: 3 },
        ],
        schema: schemaFromFields([
          { name: 'targetUserId', label: 'Target user ID', type: 'text', required: true },
          { name: 'changeType', label: 'Change type', type: 'select', required: true, options: [] },
          { name: 'roleNames', label: 'Role names', type: 'tags' },
          { name: 'reason', label: 'Reason', type: 'textarea', required: true },
        ]),
        submit: (values) => postRecord('/api/access-change-requests', values),
      },
    ],
    queries: [
      {
        key: 'users-list',
        title: 'User register',
        description: 'Visible users, current status, MFA state, and role assignment summary.',
        type: 'table',
        fetch: () => getList('/api/users'),
        entityType: 'User',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'displayName', label: 'Display name' },
          { key: 'email', label: 'Email' },
          { key: 'status', label: 'Status', kind: 'status' },
          { key: 'mfaEnabled', label: 'MFA' },
          { key: 'roles', label: 'Roles', kind: 'array' },
          { key: 'lastLoginAtUtc', label: 'Last login', kind: 'datetime' },
        ],
        rowActions: [
          {
            label: 'Reset password',
            permission: permissions.identityUsersPasswordReset,
            run: (row, note) => postRecord(`/api/users/${row.id}/password-reset`, { temporaryPassword: 'ChangeMe123!', requirePasswordChange: true, reason: note }),
          },
          {
            label: 'Enable MFA',
            permission: permissions.identityUsersMfaManage,
            run: (row, note) => postRecord(`/api/users/${row.id}/mfa`, { enabled: true, secret: note || 'admin-console-secret', factorType: 'Totp' }),
          },
          {
            label: 'Request roles',
            permission: permissions.identityAccessChangeRequest,
            run: (row, note) => postRecord(`/api/users/${row.id}/roles`, { roleNames: ['InternalAuditor'], reason: note || 'Requested from admin console.' }),
          },
        ],
      },
    ],
  },
  {
    route: '/approvals',
    title: 'Pending approvals',
    description: 'Workflow queue for maker-checker-approver actions across access, product, valuation, reporting, and operational controls.',
    icon: ClipboardCheck,
    navPermission: permissions.workflowRead,
    queries: [
      {
        key: 'workflow-pending',
        title: 'Workflow queue',
        description: 'Use only when your permission set authorizes the relevant workflow stage.',
        type: 'table',
        fetch: () => getList('/api/workflows/pending'),
        entityType: 'WorkflowInstance',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'workflowType', label: 'Workflow type' },
          { key: 'entityType', label: 'Entity type' },
          { key: 'status', label: 'Status', kind: 'status' },
          { key: 'currentStep', label: 'Current step' },
          { key: 'title', label: 'Title' },
          { key: 'createdAtUtc', label: 'Created', kind: 'datetime' },
        ],
        rowActions: [
          { label: 'Submit', permission: permissions.workflowSubmit, run: (row, note) => postRecord(`/api/workflows/${row.id}/submit`, { comment: note }) },
          { label: 'Check', permission: permissions.workflowCheck, run: (row, note) => postRecord(`/api/workflows/${row.id}/check`, { comment: note }) },
          { label: 'Approve', permission: permissions.workflowApprove, run: (row, note) => postRecord(`/api/workflows/${row.id}/approve`, { comment: note }) },
          { label: 'Reject', permission: permissions.workflowReject, run: (row, note) => postRecord(`/api/workflows/${row.id}/reject`, { comment: note }) },
        ],
      },
    ],
  },
  {
    route: '/schemes',
    title: 'Schemes and classes',
    description: 'Scheme setup, class terms, fee matrices, bank accounts, and custody mappings.',
    icon: Landmark,
    navPermission: permissions.schemesRead,
    mutations: [
      {
        key: 'create-scheme',
        title: 'Create scheme',
        permission: permissions.schemesCreate,
        fields: [
          { name: 'code', label: 'Code', type: 'text', required: true },
          { name: 'name', label: 'Name', type: 'text', required: true },
          { name: 'legalType', label: 'Legal type', type: 'text', required: true, placeholder: 'Unit Trust' },
          { name: 'baseCurrency', label: 'Base currency', type: 'text', required: true, placeholder: 'KES' },
        ],
        schema: schemaFromFields([
          { name: 'code', label: 'Code', type: 'text', required: true },
          { name: 'name', label: 'Name', type: 'text', required: true },
          { name: 'legalType', label: 'Legal type', type: 'text', required: true },
          { name: 'baseCurrency', label: 'Base currency', type: 'text', required: true },
        ]),
        submit: (values) => postRecord('/api/schemes', values),
      },
      {
        key: 'add-scheme-class',
        title: 'Add scheme class',
        permission: permissions.schemesAmend,
        fields: [
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'code', label: 'Class code', type: 'text', required: true },
          { name: 'name', label: 'Class name', type: 'text', required: true },
          { name: 'currency', label: 'Currency', type: 'text', required: true },
          { name: 'valuationFrequency', label: 'Valuation frequency', type: 'text', required: true, placeholder: 'Daily' },
          { name: 'dealingFrequency', label: 'Dealing frequency', type: 'text', required: true, placeholder: 'Daily' },
          { name: 'cutOffTime', label: 'Cut-off time', type: 'time', required: true },
          { name: 'minimumContribution', label: 'Minimum contribution', type: 'number', required: true },
          { name: 'minimumBalance', label: 'Minimum balance', type: 'number', required: true },
          { name: 'lockInDays', label: 'Lock-in days', type: 'number', required: true },
          { name: 'noticePeriodDays', label: 'Notice period days', type: 'number', required: true },
        ],
        schema: schemaFromFields([
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'code', label: 'Class code', type: 'text', required: true },
          { name: 'name', label: 'Class name', type: 'text', required: true },
          { name: 'currency', label: 'Currency', type: 'text', required: true },
          { name: 'valuationFrequency', label: 'Valuation frequency', type: 'text', required: true },
          { name: 'dealingFrequency', label: 'Dealing frequency', type: 'text', required: true },
          { name: 'cutOffTime', label: 'Cut-off time', type: 'time', required: true },
          { name: 'minimumContribution', label: 'Minimum contribution', type: 'number', required: true },
          { name: 'minimumBalance', label: 'Minimum balance', type: 'number', required: true },
          { name: 'lockInDays', label: 'Lock-in days', type: 'number', required: true },
          { name: 'noticePeriodDays', label: 'Notice period days', type: 'number', required: true },
        ]),
        submit: (values) => postRecord(`/api/schemes/${values.schemeId}/classes`, values),
      },
    ],
    queries: [
      {
        key: 'schemes-list',
        title: 'Schemes',
        description: 'Review current product setup and use workflow actions when your permission set allows it.',
        type: 'table',
        fetch: () => getList('/api/schemes'),
        entityType: 'Scheme',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'code', label: 'Code' },
          { key: 'name', label: 'Name' },
          { key: 'legalType', label: 'Legal type' },
          { key: 'baseCurrency', label: 'Currency' },
          { key: 'status', label: 'Status', kind: 'status' },
          { key: 'versionNumber', label: 'Version' },
        ],
        rowActions: [
          { label: 'Submit', permission: permissions.schemesSubmit, run: (row, note) => postRecord(`/api/schemes/${row.id}/submit`, { comment: note }) },
          { label: 'Check', permission: permissions.schemesCheck, run: (row, note) => postRecord(`/api/schemes/${row.id}/check`, { comment: note }) },
          { label: 'Approve', permission: permissions.schemesApprove, run: (row, note) => postRecord(`/api/schemes/${row.id}/approve`, { comment: note }) },
        ],
      },
    ],
  },
  {
    route: '/investors',
    title: 'Investors and KYC',
    description: 'Onboarding, document metadata, KYC completeness, and controlled approval actions.',
    icon: Users,
    navPermission: permissions.investorsRead,
    mutations: [
      {
        key: 'create-investor',
        title: 'Create individual investor',
        permission: permissions.investorsCreate,
        fields: [
          { name: 'investorType', label: 'Investor type', type: 'select', required: true, options: [{ label: 'Individual', value: 'Individual' }] },
          { name: 'displayName', label: 'Display name', type: 'text', required: true },
          { name: 'email', label: 'Email', type: 'email', required: true },
          { name: 'phoneNumber', label: 'Phone number', type: 'text', required: true },
          { name: 'riskCategory', label: 'Risk category', type: 'select', required: true, options: [{ label: 'Low', value: 'Low' }, { label: 'Medium', value: 'Medium' }, { label: 'High', value: 'High' }] },
          { name: 'riskReason', label: 'Risk rationale', type: 'textarea', required: true },
          { name: 'identityNumber', label: 'Identity number', type: 'text', required: true },
          { name: 'firstName', label: 'First name', type: 'text', required: true },
          { name: 'lastName', label: 'Last name', type: 'text', required: true },
          { name: 'dateOfBirth', label: 'Date of birth', type: 'date', required: true },
          { name: 'nationality', label: 'Nationality', type: 'text', required: true },
          { name: 'taxNumber', label: 'Tax number', type: 'text' },
          { name: 'countryOfTaxResidence', label: 'Tax residence', type: 'text' },
          { name: 'addressLine1', label: 'Address line 1', type: 'text' },
          { name: 'mandateType', label: 'Mandate type', type: 'text' },
          { name: 'signingAuthority', label: 'Signing authority', type: 'text' },
          { name: 'mandateEffectiveFrom', label: 'Mandate effective from', type: 'date' },
        ],
        schema: schemaFromFields([
          { name: 'investorType', label: 'Investor type', type: 'select', required: true, options: [] },
          { name: 'displayName', label: 'Display name', type: 'text', required: true },
          { name: 'email', label: 'Email', type: 'email', required: true },
          { name: 'phoneNumber', label: 'Phone number', type: 'text', required: true },
          { name: 'riskCategory', label: 'Risk category', type: 'select', required: true, options: [] },
          { name: 'riskReason', label: 'Risk rationale', type: 'textarea', required: true },
          { name: 'identityNumber', label: 'Identity number', type: 'text', required: true },
          { name: 'firstName', label: 'First name', type: 'text', required: true },
          { name: 'lastName', label: 'Last name', type: 'text', required: true },
          { name: 'dateOfBirth', label: 'Date of birth', type: 'date', required: true },
          { name: 'nationality', label: 'Nationality', type: 'text', required: true },
        ]),
        submit: (values) => postRecord('/api/investors', values),
      },
      {
        key: 'upload-kyc-document',
        title: 'Upload KYC metadata',
        permission: permissions.investorsDocumentsUpload,
        fields: [
          { name: 'investorId', label: 'Investor ID', type: 'text', required: true },
          { name: 'documentType', label: 'Document type', type: 'text', required: true },
          { name: 'fileName', label: 'File name', type: 'text', required: true },
          { name: 'contentType', label: 'Content type', type: 'text', required: true, placeholder: 'application/pdf' },
          { name: 'sizeBytes', label: 'Size bytes', type: 'number', required: true },
          { name: 'storageReference', label: 'Storage reference', type: 'text', required: true },
          { name: 'expiryDate', label: 'Expiry date', type: 'date' },
        ],
        schema: schemaFromFields([
          { name: 'investorId', label: 'Investor ID', type: 'text', required: true },
          { name: 'documentType', label: 'Document type', type: 'text', required: true },
          { name: 'fileName', label: 'File name', type: 'text', required: true },
          { name: 'contentType', label: 'Content type', type: 'text', required: true },
          { name: 'sizeBytes', label: 'Size bytes', type: 'number', required: true },
          { name: 'storageReference', label: 'Storage reference', type: 'text', required: true },
        ]),
        submit: (values) => postRecord(`/api/investors/${values.investorId}/documents`, values),
      },
    ],
    queries: [
      {
        key: 'investor-list',
        title: 'Investor register',
        description: 'Includes onboarding status, risk classification, and current KYC posture.',
        type: 'table',
        fetch: () => getList('/api/investors'),
        entityType: 'Investor',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'investorNumber', label: 'Investor number' },
          { key: 'displayName', label: 'Display name' },
          { key: 'email', label: 'Email' },
          { key: 'status', label: 'Status', kind: 'status' },
          { key: 'riskCategory', label: 'Risk category' },
          { key: 'submittedByUserId', label: 'Submitted by' },
        ],
        rowActions: [
          { label: 'Submit KYC', permission: permissions.investorsSubmitKyc, run: (row) => postRecord(`/api/investors/${row.id}/submit-kyc`) },
          { label: 'Approve', permission: permissions.investorsApprove, run: (row, note) => postRecord(`/api/investors/${row.id}/approve`, { comment: note }) },
          { label: 'Reject', permission: permissions.investorsReject, run: (row, note) => postRecord(`/api/investors/${row.id}/reject`, { comment: note }) },
          { label: 'AML', permission: permissions.investorsAmlScreen, run: (row, note) => postRecord(`/api/investors/${row.id}/aml-screening`, { providerName: 'ManualStub', screeningReference: note || undefined }) },
        ],
      },
      {
        key: 'expired-kyc',
        title: 'Expired KYC documents',
        type: 'table',
        requiredPermission: permissions.investorsKycRead,
        fetch: () => getList('/api/kyc/expired-documents'),
        entityType: 'Investor',
        entityId: (row) => String(row.investorId ?? ''),
        columns: [
          { key: 'investorNumber', label: 'Investor number' },
          { key: 'documentType', label: 'Document type' },
          { key: 'fileName', label: 'File name' },
          { key: 'expiryDate', label: 'Expiry date', kind: 'date' },
          { key: 'status', label: 'Status', kind: 'status' },
        ],
      },
    ],
  },
  {
    route: '/aml-exceptions',
    title: 'AML exceptions',
    description: 'Current unresolved AML, PEP, and sanctions hits requiring escalation or clearance.',
    icon: ShieldAlert,
    navPermission: permissions.investorsAmlRead,
    queries: [
      {
        key: 'aml-exceptions',
        title: 'AML exception register',
        type: 'table',
        fetch: () => getList('/api/aml/exceptions'),
        entityType: 'Investor',
        entityId: (row) => String(row.investorId ?? ''),
        columns: [
          { key: 'investorNumber', label: 'Investor number' },
          { key: 'providerName', label: 'Provider' },
          { key: 'matchedName', label: 'Matched name' },
          { key: 'riskLevel', label: 'Risk', kind: 'status' },
          { key: 'notes', label: 'Notes' },
        ],
      },
    ],
  },
  {
    route: '/dealing',
    title: 'Dealing instructions',
    description: 'Subscriptions, redemptions, switches, transfers, cut-off breaches, and recurring plans.',
    icon: BriefcaseBusiness,
    navPermission: permissions.dealingRead,
    mutations: [
      {
        key: 'create-subscription',
        title: 'Create subscription',
        permission: permissions.dealingCreate,
        fields: [
          { name: 'investorId', label: 'Investor ID', type: 'text', required: true },
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text', required: true },
          { name: 'channel', label: 'Channel', type: 'text', required: true, placeholder: 'Operations' },
          { name: 'businessDate', label: 'Business date', type: 'date', required: true },
          { name: 'mode', label: 'Mode', type: 'text', required: true, placeholder: 'Amount' },
          { name: 'amount', label: 'Amount', type: 'number', required: true },
          { name: 'currency', label: 'Currency', type: 'text', required: true, placeholder: 'KES' },
        ],
        schema: schemaFromFields([
          { name: 'investorId', label: 'Investor ID', type: 'text', required: true },
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text', required: true },
          { name: 'channel', label: 'Channel', type: 'text', required: true },
          { name: 'businessDate', label: 'Business date', type: 'date', required: true },
          { name: 'mode', label: 'Mode', type: 'text', required: true },
          { name: 'amount', label: 'Amount', type: 'number', required: true },
          { name: 'currency', label: 'Currency', type: 'text', required: true },
        ]),
        submit: (values) => postRecord('/api/dealing/subscriptions', values),
      },
    ],
    queries: [
      {
        key: 'dealing-pending',
        title: 'Pending instructions',
        type: 'table',
        fetch: () => getList('/api/dealing/pending'),
        entityType: 'DealingInstruction',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'instructionNumber', label: 'Instruction number' },
          { key: 'instructionType', label: 'Type' },
          { key: 'status', label: 'Status', kind: 'status' },
          { key: 'channel', label: 'Channel' },
          { key: 'receivedAtUtc', label: 'Received', kind: 'datetime' },
        ],
        rowActions: [
          { label: 'Submit', permission: permissions.dealingSubmit, run: (row, note) => postRecord(`/api/dealing/instructions/${row.id}/submit`, { comment: note }) },
          { label: 'Approve', permission: permissions.dealingApprove, run: (row, note) => postRecord(`/api/dealing/instructions/${row.id}/approve`, { comment: note }) },
          { label: 'Reject', permission: permissions.dealingReject, run: (row, note) => postRecord(`/api/dealing/instructions/${row.id}/reject`, { comment: note }) },
          { label: 'Cancel', permission: permissions.dealingCancel, run: (row, note) => postRecord(`/api/dealing/instructions/${row.id}/cancel`, { comment: note }) },
        ],
      },
      {
        key: 'cutoff-breaches',
        title: 'Cut-off breaches',
        type: 'table',
        fetch: () => getList('/api/dealing/cutoff-breaches'),
        entityType: 'CutOffBreach',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'instructionNumber', label: 'Instruction number' },
          { key: 'status', label: 'Status', kind: 'status' },
          { key: 'reason', label: 'Reason' },
          { key: 'receivedAtUtc', label: 'Logged', kind: 'datetime' },
        ],
      },
    ],
  },
  {
    route: '/unit-register',
    title: 'Unit register',
    description: 'Current holdings, historical positions, and controlled unit adjustments.',
    icon: Target,
    navPermission: permissions.unitRegisterRead,
    mutations: [
      {
        key: 'unit-adjustment',
        title: 'Create unit adjustment',
        permission: permissions.unitRegisterAdjustmentsCreate,
        fields: [
          { name: 'investorId', label: 'Investor ID', type: 'text', required: true },
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text', required: true },
          { name: 'valuationDate', label: 'Valuation date', type: 'date', required: true },
          { name: 'units', label: 'Units', type: 'number', required: true },
          { name: 'reason', label: 'Reason', type: 'textarea', required: true },
        ],
        schema: schemaFromFields([
          { name: 'investorId', label: 'Investor ID', type: 'text', required: true },
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text', required: true },
          { name: 'valuationDate', label: 'Valuation date', type: 'date', required: true },
          { name: 'units', label: 'Units', type: 'number', required: true },
          { name: 'reason', label: 'Reason', type: 'textarea', required: true },
        ]),
        submit: (values) => postRecord('/api/unit-register/adjustments', values),
      },
    ],
    queries: [
      {
        key: 'unit-holdings',
        title: 'Investor holdings',
        type: 'table',
        fetch: (query) => getList(`/api/unit-register/investors/${query.investorId}/holdings`),
        queryFields: [{ name: 'investorId', label: 'Investor ID', type: 'text', required: true }],
        entityType: 'UnitHolding',
        entityId: (row) => String(row.id ?? row.schemeClassId ?? ''),
        columns: [
          { key: 'schemeId', label: 'Scheme ID' },
          { key: 'schemeClassId', label: 'Scheme class ID' },
          { key: 'units', label: 'Units', kind: 'money' },
          { key: 'redeemableUnits', label: 'Redeemable', kind: 'money' },
          { key: 'lastTransactionReference', label: 'Last reference' },
        ],
      },
      {
        key: 'historical-holdings',
        title: 'Historical reconstruction',
        type: 'table',
        fetch: (query) => getList(`/api/unit-register/investors/${query.investorId}/historical`, { date: query.date }),
        queryFields: [
          { name: 'investorId', label: 'Investor ID', type: 'text', required: true },
          { name: 'date', label: 'Valuation date', type: 'date', required: true },
        ],
        entityType: 'HistoricalHoldingView',
        entityId: (row) => String(row.unitLedgerEntryId ?? row.transactionReference ?? ''),
        columns: [
          { key: 'schemeId', label: 'Scheme ID' },
          { key: 'schemeClassId', label: 'Scheme class ID' },
          { key: 'valuationDate', label: 'Valuation date', kind: 'date' },
          { key: 'transactionReference', label: 'Reference' },
          { key: 'closingUnits', label: 'Closing units', kind: 'money' },
        ],
      },
    ],
  },
  {
    route: '/cash',
    title: 'Cash reconciliation',
    description: 'Bank statement imports, suspense items, reconciliation runs, payout tracking, and reversals.',
    icon: Wallet,
    navPermission: permissions.cashRead,
    mutations: [
      {
        key: 'cash-reconciliation-run',
        title: 'Create cash reconciliation run',
        permission: permissions.cashReconciliationRunsCreate,
        fields: [
          { name: 'schemeBankAccountId', label: 'Scheme bank account ID', type: 'text', required: true },
          { name: 'runDate', label: 'Run date', type: 'date', required: true },
        ],
        schema: schemaFromFields([
          { name: 'schemeBankAccountId', label: 'Scheme bank account ID', type: 'text', required: true },
          { name: 'runDate', label: 'Run date', type: 'date', required: true },
        ]),
        submit: (values) => postRecord('/api/cash/reconciliation-runs', values),
      },
    ],
    queries: [
      {
        key: 'cash-suspense',
        title: 'Suspense register',
        type: 'table',
        fetch: () => getList('/api/cash/suspense'),
        entityType: 'SuspenseItem',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'reference', label: 'Reference' },
          { key: 'status', label: 'Status', kind: 'status' },
          { key: 'amount', label: 'Amount', kind: 'money' },
          { key: 'openedAtUtc', label: 'Opened', kind: 'datetime' },
          { key: 'reason', label: 'Reason' },
        ],
        rowActions: [
          { label: 'Resolve', permission: permissions.cashSuspenseResolve, run: (row, note) => postRecord(`/api/cash/suspense/${row.id}/resolve`, { resolutionReference: note || 'ADMIN-CONSOLE', reason: note || 'Resolved from admin console.' }) },
        ],
      },
    ],
  },
  {
    route: '/portfolio',
    title: 'Portfolio holdings',
    description: 'Instruments, counterparties, placements, holdings, maturity ladders, and income due views.',
    icon: Building2,
    navPermission: permissions.portfolioRead,
    mutations: [
      {
        key: 'portfolio-placement',
        title: 'Create placement',
        permission: permissions.portfolioPlacementsCreate,
        fields: [
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text', required: true },
          { name: 'instrumentId', label: 'Instrument ID', type: 'text', required: true },
          { name: 'counterpartyId', label: 'Counterparty ID', type: 'text', required: true },
          { name: 'tradeDate', label: 'Trade date', type: 'date', required: true },
          { name: 'settlementDate', label: 'Settlement date', type: 'date', required: true },
          { name: 'quantity', label: 'Quantity', type: 'number', required: true },
          { name: 'price', label: 'Price', type: 'number', required: true },
        ],
        schema: schemaFromFields([
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text', required: true },
          { name: 'instrumentId', label: 'Instrument ID', type: 'text', required: true },
          { name: 'counterpartyId', label: 'Counterparty ID', type: 'text', required: true },
          { name: 'tradeDate', label: 'Trade date', type: 'date', required: true },
          { name: 'settlementDate', label: 'Settlement date', type: 'date', required: true },
          { name: 'quantity', label: 'Quantity', type: 'number', required: true },
          { name: 'price', label: 'Price', type: 'number', required: true },
        ]),
        submit: (values) => postRecord('/api/portfolio/placements', values),
      },
    ],
    queries: [
      {
        key: 'portfolio-holdings',
        title: 'Holdings',
        type: 'table',
        fetch: (query) => getList('/api/portfolio/holdings', query),
        queryFields: [
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text', required: true },
        ],
        entityType: 'PortfolioHolding',
        entityId: (row) => String(row.instrumentId ?? row.id ?? ''),
        columns: [
          { key: 'instrumentName', label: 'Instrument' },
          { key: 'assetClass', label: 'Asset class' },
          { key: 'quantity', label: 'Quantity', kind: 'money' },
          { key: 'marketValue', label: 'Market value', kind: 'money' },
          { key: 'status', label: 'Status', kind: 'status' },
        ],
      },
    ],
  },
  {
    route: '/nav',
    title: 'NAV runs',
    description: 'Valuation runs, overrides, reconstructions, and publication history.',
    icon: Scale,
    navPermission: permissions.navRead,
    mutations: [
      {
        key: 'nav-run',
        title: 'Create valuation run',
        permission: permissions.navValuationRunsCreate,
        fields: [
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text', required: true },
          { name: 'valuationDate', label: 'Valuation date', type: 'date', required: true },
          { name: 'dayCountBasis', label: 'Day-count basis', type: 'text', required: true, placeholder: 'Actual365' },
        ],
        schema: schemaFromFields([
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text', required: true },
          { name: 'valuationDate', label: 'Valuation date', type: 'date', required: true },
          { name: 'dayCountBasis', label: 'Day-count basis', type: 'text', required: true },
        ]),
        submit: (values) => postRecord('/api/nav/valuation-runs', values),
      },
    ],
    queries: [
      {
        key: 'nav-history',
        title: 'NAV publication history',
        type: 'table',
        fetch: (query) => getList('/api/nav/history', query),
        queryFields: [
          { name: 'schemeId', label: 'Scheme ID', type: 'text' },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text' },
          { name: 'fromDate', label: 'From date', type: 'date' },
          { name: 'toDate', label: 'To date', type: 'date' },
        ],
        entityType: 'NavPublication',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'schemeId', label: 'Scheme ID' },
          { key: 'schemeClassId', label: 'Scheme class ID' },
          { key: 'valuationDate', label: 'Valuation date', kind: 'date' },
          { key: 'versionNumber', label: 'Version' },
          { key: 'status', label: 'Status', kind: 'status' },
          { key: 'publishedAtUtc', label: 'Published', kind: 'datetime' },
        ],
      },
      {
        key: 'nav-reconstruct',
        title: 'Historical NAV reconstruction',
        type: 'record',
        fetch: (query) => getRecord('/api/nav/reconstruct', query),
        queryFields: [
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'valuationDate', label: 'Valuation date', type: 'date', required: true },
        ],
      },
    ],
  },
  {
    route: '/accounting',
    title: 'Accounting journals',
    description: 'Chart setup, manual journals, ledger views, trial balance, and NAV reconciliation.',
    icon: BookCheck,
    navPermission: permissions.accountingRead,
    mutations: [
      {
        key: 'manual-journal',
        title: 'Create manual journal',
        permission: permissions.accountingJournalsManualCreate,
        fields: [
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text' },
          { name: 'journalType', label: 'Journal type', type: 'text', required: true },
          { name: 'postingDate', label: 'Posting date', type: 'date', required: true },
          { name: 'description', label: 'Description', type: 'textarea', required: true },
          { name: 'lines', label: 'Journal lines (JSON)', type: 'textarea', required: true, rows: 6, helpText: 'Provide the expected line array in JSON format.' },
        ],
        schema: schemaFromFields([
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'journalType', label: 'Journal type', type: 'text', required: true },
          { name: 'postingDate', label: 'Posting date', type: 'date', required: true },
          { name: 'description', label: 'Description', type: 'textarea', required: true },
          { name: 'lines', label: 'Journal lines (JSON)', type: 'textarea', required: true },
        ]),
        submit: (values) => postRecord('/api/accounting/journals/manual', {
          ...values,
          lines: typeof values.lines === 'string' ? JSON.parse(values.lines) : values.lines,
        }),
      },
    ],
    queries: [
      {
        key: 'journal-register',
        title: 'Journal register',
        type: 'record',
        fetch: (query) => getRecord('/api/accounting/journal-register', query),
        queryFields: [
          { name: 'schemeId', label: 'Scheme ID', type: 'text' },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text' },
          { name: 'fromDate', label: 'From date', type: 'date' },
          { name: 'toDate', label: 'To date', type: 'date' },
        ],
      },
      {
        key: 'trial-balance',
        title: 'Trial balance',
        type: 'record',
        fetch: (query) => getRecord('/api/accounting/trial-balance', query),
        queryFields: [
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text' },
          { name: 'asOfDate', label: 'As of date', type: 'date', required: true },
        ],
      },
    ],
  },
  {
    route: '/fees-tax-distributions',
    title: 'Fee, tax, and distribution runs',
    description: 'Fee accruals, waivers, tax rules, declarations, publications, and investor distribution views.',
    icon: BadgeDollarSign,
    navPermission: permissions.feesRead,
    mutations: [
      {
        key: 'fee-accrual',
        title: 'Create fee accrual run',
        permission: permissions.feesAccrualRunsCreate,
        fields: [
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text' },
          { name: 'businessDate', label: 'Business date', type: 'date', required: true },
        ],
        schema: schemaFromFields([
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'businessDate', label: 'Business date', type: 'date', required: true },
        ]),
        submit: (values) => postRecord('/api/fees/accrual-runs', values),
      },
      {
        key: 'distribution-run',
        title: 'Create distribution run',
        permission: permissions.distributionsCreate,
        fields: [
          { name: 'declarationId', label: 'Declaration ID', type: 'text', required: true },
          { name: 'paymentDate', label: 'Payment date', type: 'date', required: true },
        ],
        schema: schemaFromFields([
          { name: 'declarationId', label: 'Declaration ID', type: 'text', required: true },
          { name: 'paymentDate', label: 'Payment date', type: 'date', required: true },
        ]),
        submit: (values) => postRecord('/api/distributions/runs', values),
      },
    ],
    queries: [
      {
        key: 'accrual-run',
        title: 'Accrual run lookup',
        type: 'record',
        fetch: (query) => getRecord(`/api/fees/accrual-runs/${query.id}`),
        queryFields: [{ name: 'id', label: 'Accrual run ID', type: 'text', required: true }],
      },
      {
        key: 'investor-distributions',
        title: 'Investor distributions',
        type: 'table',
        fetch: (query) => getList(`/api/distributions/investor/${query.investorId}`),
        queryFields: [{ name: 'investorId', label: 'Investor ID', type: 'text', required: true }],
        entityType: 'InvestorDistribution',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'distributionReference', label: 'Reference' },
          { key: 'status', label: 'Status', kind: 'status' },
          { key: 'grossDistribution', label: 'Gross', kind: 'money' },
          { key: 'netDistribution', label: 'Net', kind: 'money' },
          { key: 'paymentDate', label: 'Payment date', kind: 'date' },
        ],
      },
    ],
  },
  {
    route: '/compliance',
    title: 'Compliance breaches',
    description: 'Limit checks, breach ownership, remediation evidence, liquidity, and dashboard visibility.',
    icon: AlertCircle,
    navPermission: permissions.complianceRead,
    mutations: [
      {
        key: 'limit-run',
        title: 'Create limit run',
        permission: permissions.complianceLimitRunsCreate,
        fields: [
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text' },
          { name: 'businessDate', label: 'Business date', type: 'date', required: true },
        ],
        schema: schemaFromFields([
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'businessDate', label: 'Business date', type: 'date', required: true },
        ]),
        submit: (values) => postRecord('/api/compliance/limit-runs', values),
      },
    ],
    queries: [
      {
        key: 'breaches',
        title: 'Breach register',
        type: 'table',
        fetch: (query) => getList('/api/compliance/breaches', query),
        queryFields: [{ name: 'status', label: 'Status filter', type: 'text' }],
        entityType: 'LimitBreach',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'limitType', label: 'Limit type' },
          { key: 'reference', label: 'Reference' },
          { key: 'severity', label: 'Severity', kind: 'status' },
          { key: 'status', label: 'Status', kind: 'status' },
          { key: 'ownerUserId', label: 'Owner' },
        ],
        rowActions: [
          { label: 'Assign', permission: permissions.complianceBreachesManage, run: (row, note) => postRecord(`/api/compliance/breaches/${row.id}/assign`, { ownerUserId: note || 'admin-console', comment: note || 'Assigned from admin console.' }) },
          { label: 'Remediate', permission: permissions.complianceBreachesManage, run: (row, note) => postRecord(`/api/compliance/breaches/${row.id}/remediate`, { actionDescription: note || 'Remediation in progress.', evidenceReference: note || 'ADMIN-CONSOLE' }) },
          { label: 'Close', permission: permissions.complianceBreachesClose, run: (row, note) => postRecord(`/api/compliance/breaches/${row.id}/close`, { evidenceReference: note || 'ADMIN-CONSOLE', comment: note || 'Closed from admin console.' }) },
        ],
      },
      {
        key: 'risk-dashboard',
        title: 'Risk dashboard',
        type: 'record',
        fetch: () => getRecord('/api/risk/dashboard'),
      },
    ],
  },
  {
    route: '/custody',
    title: 'Custody reconciliation breaks',
    description: 'Custodian imports, reconciliation runs, break ownership, and resolution evidence.',
    icon: FileWarning,
    navPermission: permissions.custodyRead,
    mutations: [
      {
        key: 'custody-run',
        title: 'Create custody reconciliation run',
        permission: permissions.custodyReconciliationRunsCreate,
        fields: [
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'schemeClassId', label: 'Scheme class ID', type: 'text' },
          { name: 'businessDate', label: 'Business date', type: 'date', required: true },
        ],
        schema: schemaFromFields([
          { name: 'schemeId', label: 'Scheme ID', type: 'text', required: true },
          { name: 'businessDate', label: 'Business date', type: 'date', required: true },
        ]),
        submit: (values) => postRecord('/api/custody/reconciliation-runs', values),
      },
    ],
    queries: [
      {
        key: 'custody-breaks',
        title: 'Reconciliation breaks',
        type: 'table',
        fetch: (query) => getList('/api/custody/reconciliation-breaks', query),
        queryFields: [{ name: 'status', label: 'Status filter', type: 'text' }],
        entityType: 'CustodyReconciliationBreak',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'breakType', label: 'Break type' },
          { key: 'status', label: 'Status', kind: 'status' },
          { key: 'ownerUserId', label: 'Owner' },
          { key: 'ageDays', label: 'Age (days)' },
          { key: 'differenceAmount', label: 'Difference', kind: 'money' },
        ],
        rowActions: [
          { label: 'Assign', permission: permissions.custodyBreaksManage, run: (row, note) => postRecord(`/api/custody/reconciliation-breaks/${row.id}/assign`, { ownerUserId: note || 'admin-console', note: note || 'Assigned from admin console.' }) },
          { label: 'Resolve', permission: permissions.custodyBreaksResolve, run: (row, note) => postRecord(`/api/custody/reconciliation-breaks/${row.id}/resolve`, { resolutionReference: note || 'ADMIN-CONSOLE', evidenceReference: note || 'ADMIN-CONSOLE' }) },
        ],
      },
    ],
  },
  {
    route: '/reports',
    title: 'Reports',
    description: 'Report registry, run history, approvals, publication, bundles, CSV exports, and archive-friendly distribution.',
    icon: FileSearch,
    navPermission: permissions.reportsRead,
    mutations: [
      {
        key: 'run-report',
        title: 'Run report',
        permission: permissions.reportsRun,
        fields: [
          { name: 'code', label: 'Report code', type: 'text', required: true, placeholder: 'REG-01' },
          { name: 'businessDate', label: 'Business date', type: 'date', required: true },
        ],
        schema: schemaFromFields([
          { name: 'code', label: 'Report code', type: 'text', required: true },
          { name: 'businessDate', label: 'Business date', type: 'date', required: true },
        ]),
        submit: (values) => postRecord(`/api/reports/${values.code}/run`, values),
      },
    ],
    queries: [
      {
        key: 'report-definitions',
        title: 'Report catalogue',
        type: 'table',
        fetch: () => getList('/api/reports/definitions'),
        entityType: 'ReportDefinition',
        entityId: (row) => String(row.id ?? row.code ?? ''),
        columns: [
          { key: 'code', label: 'Code' },
          { key: 'name', label: 'Name' },
          { key: 'category', label: 'Category' },
          { key: 'frequency', label: 'Frequency' },
          { key: 'requiredPermission', label: 'Required permission' },
        ],
      },
      {
        key: 'report-runs',
        title: 'Report runs',
        type: 'table',
        fetch: () => getList('/api/reports/runs'),
        entityType: 'ReportRun',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'reportCode', label: 'Report code' },
          { key: 'status', label: 'Status', kind: 'status' },
          { key: 'businessDate', label: 'Business date', kind: 'date' },
          { key: 'generatedAtUtc', label: 'Generated', kind: 'datetime' },
          { key: 'versionNumber', label: 'Version' },
        ],
        rowActions: [
          { label: 'Approve', permission: permissions.reportsApprove, run: (row, note) => postRecord(`/api/reports/runs/${row.id}/approve`, { comment: note }) },
          { label: 'Publish', permission: permissions.reportsPublish, run: (row, note) => postRecord(`/api/reports/runs/${row.id}/publish`, { comment: note }) },
        ],
      },
    ],
  },
  {
    route: '/audit',
    title: 'Audit logs',
    description: 'Central append-only audit history across actions, workflows, approvals, and security events.',
    icon: FolderLock,
    navPermission: permissions.auditRead,
    queries: [
      {
        key: 'audit-all',
        title: 'Audit event stream',
        type: 'table',
        fetch: () => getList('/api/audit-logs'),
        entityType: 'AuditLog',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'module', label: 'Module' },
          { key: 'action', label: 'Action' },
          { key: 'entityName', label: 'Entity' },
          { key: 'actorDisplayName', label: 'Actor' },
          { key: 'occurredAtUtc', label: 'Occurred', kind: 'datetime' },
          { key: 'reason', label: 'Reason' },
        ],
      },
    ],
  },
  {
    route: '/data-quality',
    title: 'Data quality exceptions',
    description: 'Rule administration, check runs, exception queue ownership, and remediation evidence.',
    icon: Activity,
    navPermission: permissions.dataQualityRead,
    mutations: [
      {
        key: 'data-quality-check',
        title: 'Run data quality checks',
        permission: permissions.dataQualityCheckRunsCreate,
        fields: [],
        schema: schemaFromFields([]),
        submitLabel: 'Run checks',
        submit: () => postRecord('/api/data-quality/check-runs'),
      },
    ],
    queries: [
      {
        key: 'data-quality-exceptions',
        title: 'Exception queue',
        type: 'table',
        fetch: () => getList('/api/data-quality/exceptions'),
        entityType: 'DataQualityException',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'ruleCode', label: 'Rule' },
          { key: 'status', label: 'Status', kind: 'status' },
          { key: 'severity', label: 'Severity', kind: 'status' },
          { key: 'entityType', label: 'Entity type' },
          { key: 'entityId', label: 'Entity ID' },
          { key: 'dueAtUtc', label: 'Due', kind: 'datetime' },
        ],
        rowActions: [
          { label: 'Assign', permission: permissions.dataQualityExceptionsManage, run: (row, note) => postRecord(`/api/data-quality/exceptions/${row.id}/assign`, { ownerUserId: note || 'admin-console', comment: note || 'Assigned from admin console.' }) },
          { label: 'Resolve', permission: permissions.dataQualityExceptionsResolve, run: (row, note) => postRecord(`/api/data-quality/exceptions/${row.id}/resolve`, { resolutionEvidence: note || 'ADMIN-CONSOLE', comment: note || 'Resolved from admin console.' }) },
        ],
      },
      {
        key: 'data-quality-dashboard',
        title: 'Data quality dashboard',
        type: 'record',
        fetch: () => getRecord('/api/data-quality/dashboard'),
      },
    ],
  },
  {
    route: '/operations',
    title: 'Operations health',
    description: 'Deep health status, backup history, and DR test records for operational readiness oversight.',
    icon: AlertCircle,
    navPermission: permissions.operationsRead,
    mutations: [
      {
        key: 'dr-test',
        title: 'Schedule DR test',
        permission: permissions.operationsDrTestsManage,
        fields: [
          { name: 'testName', label: 'Test name', type: 'text', required: true },
          { name: 'environment', label: 'Environment', type: 'text', required: true, placeholder: 'Production' },
          { name: 'scenario', label: 'Scenario', type: 'textarea', required: true },
          { name: 'plannedAtUtc', label: 'Planned at', type: 'datetime-local', required: true },
          { name: 'evidenceReference', label: 'Evidence reference', type: 'text' },
        ],
        schema: schemaFromFields([
          { name: 'testName', label: 'Test name', type: 'text', required: true },
          { name: 'environment', label: 'Environment', type: 'text', required: true },
          { name: 'scenario', label: 'Scenario', type: 'textarea', required: true },
          { name: 'plannedAtUtc', label: 'Planned at', type: 'datetime-local', required: true },
        ]),
        submit: (values) => postRecord('/api/operations/dr-tests', values),
      },
    ],
    queries: [
      {
        key: 'operations-health',
        title: 'Deep health',
        type: 'record',
        requiredPermission: permissions.operationsHealthRead,
        fetch: () => getRecord('/api/operations/health/deep'),
      },
      {
        key: 'backup-runs',
        title: 'Backup runs',
        type: 'table',
        requiredPermission: permissions.operationsBackupRead,
        fetch: () => getList('/api/operations/backup-runs'),
        entityType: 'BackupRunRecord',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'databaseName', label: 'Database' },
          { key: 'backupType', label: 'Backup type' },
          { key: 'status', label: 'Status', kind: 'status' },
          { key: 'startedAtUtc', label: 'Started', kind: 'datetime' },
          { key: 'completedAtUtc', label: 'Completed', kind: 'datetime' },
        ],
      },
      {
        key: 'dr-tests',
        title: 'DR tests',
        type: 'table',
        fetch: () => getList('/api/operations/dr-tests'),
        entityType: 'DRTestRecord',
        entityId: (row) => String(row.id ?? ''),
        columns: [
          { key: 'testName', label: 'Test name' },
          { key: 'environment', label: 'Environment' },
          { key: 'status', label: 'Status', kind: 'status' },
          { key: 'plannedAtUtc', label: 'Planned', kind: 'datetime' },
          { key: 'requestedByUserId', label: 'Requested by' },
        ],
      },
    ],
  },
];
