apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cis-api-storage
  namespace: victory-cis
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cis-backups
  namespace: victory-cis
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
